DROP TABLE IF EXISTS film_genre CASCADE;
DROP TABLE IF EXISTS friendship CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS rating CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS film_director CASCADE;
DROP TABLE IF EXISTS directors CASCADE;


CREATE TABLE IF NOT EXISTS users (
	user_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	email varchar NOT NULL,
	login varchar NOT NULL,
	name varchar NOT NULL,
	birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS friendship (
	user_id int NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
	friend_id int NOT null REFERENCES users(user_id) ON DELETE CASCADE,
	PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS rating (
	rating_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	name varchar NOT NULL,
	description varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS directors (
    director_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    director_name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
	film_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	name varchar NOT NULL,
	description varchar NOT NULL,
	release_date date NOT NULL,
	duration int NOT NULL,
	rating_id int NOT NULL REFERENCES rating(rating_id) ON DELETE RESTRICT,
	likes_count int NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS film_director (
    film_id int NOT NULL REFERENCES films(film_id) ON DELETE CASCADE,
    director_id int REFERENCES directors(director_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS genres (
	genre_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	genre_name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genre (
	film_id int NOT NULL REFERENCES films(film_id) ON DELETE CASCADE,
	genre_id int  NOT NULL REFERENCES genres(genre_id) ON DELETE RESTRICT,
	PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS likes (
	film_id int NOT NULL REFERENCES films(film_id) ON DELETE CASCADE,
	user_id int NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
	PRIMARY KEY (film_id, user_id)
);
